services:
  catalog:
    uri: http://localhost:8081
    registration-id: keycloak
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/stock
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: 9aZJxk3boVkRn9XyYavT66coHx4d9oOd
            scope:
              - openid
              - view_catalog
              - edit_catalog
              - microprofile-jwt




#  keycloak:
#  docker run --name stock-keycloak -p 8082:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin -v /config/keycloak/import:/opt/keycloak/data/import quay.io/keycloak/keycloak:latest start-dev --import-realm